"""Add total_seats and price_per_seat to shows, status to bookings

Revision ID: 5b8d06475c6b
Revises: 520382e34321
Create Date: 2026-01-23 15:57:28.305757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b8d06475c6b'
down_revision: Union[str, Sequence[str], None] = '520382e34321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('shows', sa.Column('total_seats', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('price_per_seat', sa.Float(), nullable=False))
    op.alter_column('shows', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('shows', 'screen_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('shows', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('shows', 'available_seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('shows', 'price')
    op.drop_column('shows', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('end_time', mysql.DATETIME(), nullable=False))
    op.add_column('shows', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.alter_column('shows', 'available_seats',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('shows', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('shows', 'screen_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('shows', 'price_per_seat')
    op.drop_column('shows', 'total_seats')
    op.drop_column('bookings', 'status')
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###
